spring.application.name=medicareai

spring.datasource.url= jdbc:mysql://localhost:3306/medicare_ai
spring.datasource.username= root
spring.datasource.password= Biku@2004

spring.jpa.hibernate.ddl-auto= update
spring.hibernate.show-sql= true
